import {test,expect} from '@playwright/test';
import groups from '../../data/male-detail-groups.json' with {type:'json'};
import {ready,snapshot,organs} from './helpers';

test('male pancreas source views stay separate, expose original parts and return to the prior peel',async({page})=>{
  test.setTimeout(150000);
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  const whole=groups.find(group=>group.id==='pancreas')!;
  const inner=groups.find(group=>group.id==='pancreas-parenchyma')!;
  const visible=async()=>(await page.locator('canvas').getAttribute('data-visible-structure-ids')||'').split(',').filter(Boolean).sort();
  await page.setViewportSize({width:1440,height:900});await page.goto('/');await ready(page);
  await page.getByLabel('연속 해부 박리 깊이').fill('50.5');await ready(page);
  const before=await snapshot(page),canvas=page.locator('canvas');
  const beforeIds=await canvas.getAttribute('data-visible-structure-ids');
  await (await organs(page)).filter({has:page.getByText(whole.name,{exact:true})}).click();await ready(page);
  expect((await snapshot(page)).detail.id).toBe('pancreas');
  await expect.poll(visible).toEqual([...whole.ids].sort());
  await expect(page.locator('[data-pancreas-provenance]')).toContainText('BodyParts3D 4.0');
  await page.screenshot({path:'docs/anatomy-alignment/male-pancreas-whole-desktop.png'});
  await page.getByRole('button',{name:'췌장 실질·관 가지 별도 보기'}).click();await ready(page);
  expect((await snapshot(page)).detail.id).toBe('pancreas-parenchyma');
  await expect.poll(visible).toEqual([...inner.ids].sort());
  await page.locator('.organ-detail-parts summary').click();
  await expect(page.locator('.organ-detail-parts button')).toHaveCount(2);
  await page.locator('.organ-detail-parts button').last().click();await ready(page);
  expect((await snapshot(page)).selection.ids).toEqual([inner.ids[1]]);
  await page.reload();await ready(page);
  expect((await snapshot(page)).detail.id).toBe('pancreas-parenchyma');
  await expect.poll(visible).toEqual([inner.ids[1]]);
  await page.getByRole('button',{name:'기관 전체 모형',exact:true}).click();await ready(page);
  await expect.poll(visible).toEqual([...inner.ids].sort());
  await page.setViewportSize({width:390,height:844});
  const card=await page.locator('.selection-card').boundingBox();
  const movement=await page.locator('.movement-pad').boundingBox();
  // The phone tool column sits beside the card: the two never overlap.
  expect(Math.max(card!.y-(movement!.y+movement!.height),movement!.y-(card!.y+card!.height),card!.x-(movement!.x+movement!.width),movement!.x-(card!.x+card!.width))).toBeGreaterThan(4);
  await page.screenshot({path:'docs/anatomy-alignment/male-pancreas-alternative-mobile.png'});
  await page.getByRole('button',{name:'전신으로 돌아가기',exact:true}).click();await ready(page);
  const after=await snapshot(page);
  expect(after.detail).toBe(null);
  expect(after.dissection).toBe(50.5);
  expect(after.layers).toEqual(before.layers);
  await expect(canvas).toHaveAttribute('data-visible-structure-ids',beforeIds!);
  await page.locator('.ax-top').getByRole('button',{name:'여성',exact:true}).click();await ready(page);
  expect((await canvas.getAttribute('data-visible-structure-ids')||'').split(',').every(id=>!id.startsWith('BP4_'))).toBe(true);
  expect(errors).toEqual([]);
});
