import {test,expect} from '@playwright/test';
import groups from '../../data/male-detail-groups.json' with {type:'json'};
import {ready,snapshot,organs} from './helpers';

test('male kidney detail exposes original kidney, ureter and artery meshes and restores peeling',async({page})=>{
  test.setTimeout(150000);
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  const group=groups.find(group=>group.id==='kidney')!;
  const visible=async()=>(await page.locator('canvas').getAttribute('data-visible-structure-ids')||'').split(',').filter(Boolean).sort();
  await page.setViewportSize({width:1440,height:900});await page.goto('/');await ready(page);
  await page.getByLabel('연속 해부 박리 깊이').fill('50.5');await ready(page);
  const before=await snapshot(page),canvas=page.locator('canvas');
  const beforeIds=await canvas.getAttribute('data-visible-structure-ids');
  await (await organs(page)).filter({has:page.getByText(group.name,{exact:true})}).click();await ready(page);
  expect((await snapshot(page)).detail.id).toBe('kidney');
  await expect.poll(visible).toEqual([...group.ids].sort());
  const opened=await snapshot(page);
  expect(opened.layers.organ).toBe(true);
  expect(opened.layers.vessel).toBe(true);
  await page.screenshot({path:'docs/anatomy-alignment/male-kidney-detail-desktop.png'});
  await page.getByRole('button',{name:'왼쪽 콩팥·혈관 확대 보기'}).click();await ready(page);
  const leftIds=['FJ3145','FJ2046','FJ2049','FJ2052','FJ2053','FJ2054',
    'FJ3458','FJ3459','FJ3460','FJ3461','FJ3462','FJ3463','FJ3473','FJ3474','FJ3475','FJ3477','FJ3478'].map(id=>`BP4_${id}`);
  expect((await snapshot(page)).detail.id).toBe('kidney-left');
  await expect.poll(visible).toEqual([...leftIds].sort());
  await page.screenshot({path:'docs/anatomy-alignment/male-kidney-left-desktop.png'});
  await page.locator('.organ-detail-parts summary').click();
  await expect(page.locator('.organ-detail-parts button')).toHaveCount(17);
  await page.locator('.organ-detail-parts button').filter({hasText:'왼쪽 신장동맥 위구역가지'}).click();await ready(page);
  expect((await snapshot(page)).detail.id).toBe('kidney-left');
  expect((await snapshot(page)).selection.ids).toEqual(['BP4_FJ2052']);
  await expect.poll(visible).toEqual(['BP4_FJ2052']);
  await page.reload();await ready(page);
  expect((await snapshot(page)).detail.id).toBe('kidney-left');
  await expect.poll(visible).toEqual(['BP4_FJ2052']);
  await page.locator('[data-kidney-provenance] summary').click();
  await page.getByRole('button',{name:'양쪽 콩팥 전체 보기'}).click();await ready(page);
  await expect.poll(visible).toEqual([...group.ids].sort());
  await page.getByRole('button',{name:'오른쪽 콩팥·혈관 확대 보기'}).click();await ready(page);
  expect((await snapshot(page)).detail.id).toBe('kidney-right');
  await expect.poll(async()=>(await visible()).length).toBe(16);
  await page.getByRole('button',{name:'양쪽 콩팥 전체 보기'}).click();await ready(page);
  await expect.poll(visible).toEqual([...group.ids].sort());
  await page.setViewportSize({width:390,height:844});
  const card=await page.locator('.selection-card').boundingBox();
  const movement=await page.locator('.movement-pad').boundingBox();
  // The phone tool column sits beside the card: the two never overlap.
  expect(Math.max(card!.y-(movement!.y+movement!.height),movement!.y-(card!.y+card!.height),card!.x-(movement!.x+movement!.width),movement!.x-(card!.x+card!.width))).toBeGreaterThan(4);
  await page.screenshot({path:'docs/anatomy-alignment/male-kidney-detail-mobile.png'});
  await page.getByRole('button',{name:'전신으로 돌아가기',exact:true}).click();await ready(page);
  const after=await snapshot(page);
  expect(after.detail).toBe(null);
  expect(after.dissection).toBe(50.5);
  expect(after.layers).toEqual(before.layers);
  await expect.poll(async()=>(await snapshot(page)).camera).toEqual(before.camera);
  await expect(canvas).toHaveAttribute('data-visible-structure-ids',beforeIds!);
  await page.locator('.ax-top').getByRole('button',{name:'여성',exact:true}).click();await ready(page);
  expect((await visible()).every(id=>!id.startsWith('BP4_'))).toBe(true);
  expect(errors).toEqual([]);
});
