import fs from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const dir='docs/anatomy-alignment/',read=p=>fs.readFileSync(p),json=p=>JSON.parse(read(p)),sha=b=>createHash('sha256').update(b).digest('hex');
const r=json(dir+'hip-relational-flow.json'),a=json(dir+'hip-relational-flow-readback.json'),c=json(dir+'hip-relational-flow-captures.json'),prior=json(r.priorFile);
test('selected pelvic controls query open targets against closed muscles, with three ligament holdouts',()=>{
  assert.match(r.status,/NO RUNTIME EXPORT/);assert.equal(r.priorSha256,sha(read(r.priorFile)));assert.deepEqual(r.initialBinary,prior.binary);assert.deepEqual(r.boneInitialFiles,[dir+'hip-joint-flow.json',dir+'hip-adaptive-flow.json']);assert.equal(r.controls.length,32);assert.equal(r.controls.reduce((n,p)=>n+p.points,0),6273);assert.equal(r.relationMaterialControls.length,365);
  const eligible=r.relationSeeds.filter(p=>p.eligible),held=r.relationSeeds.filter(p=>!p.eligible);assert.equal(eligible.length,7);assert.deepEqual(eligible.map(p=>p.targetTopology.boundaryEdges),[83,16,66,15,16,32,32]);assert.deepEqual(held.map(p=>p.targetId),['HRAF0419','HRAF0421','HRAF0423']);assert.ok(held.every(p=>p.selectedQueryIndices.length===0));assert.ok(r.relationSeeds.every(p=>p.muscleTopology.connectedComponents===1&&p.muscleTopology.boundaryEdges===0&&p.muscleTopology.nonManifoldEdges===0&&p.muscleTopology.degenerateTriangles===0));assert.equal(r.options.relationBandMetres,.000001);assert.equal(r.options.relationTargetOffsetMetres,.00025);assert.equal(r.fit.steps.length,160);assert.equal(r.fit.termination,'iteration-limit');assert.ok(r.fit.history.every(p=>p.accepted&&p.backtracks===0&&p.afterLoss<p.beforeLoss-1e-15));
});
test('all seven eligible pairs keep crossings despite fewer inside target vertices',()=>{
  const eligible=r.relationContainment.filter(p=>p.eligible);assert.deepEqual(eligible.map(p=>[p.vertices.initial.inside,p.vertices.after.inside]),[[3,1],[19,5],[65,30],[77,25],[63,19],[52,18],[73,45]]);assert.deepEqual(eligible.map(p=>[p.area.initial.inside,p.area.after.inside]),[[0,0],[23,5],[96,44],[121,43],[82,23],[148,84],[239,151]]);assert.equal(r.relationContainment.reduce((n,p)=>n+p.queries.length,0),8810);
  for(const p of r.relationContainment){assert.equal(r.relations.find(q=>q.ids.join('/')===p.key).after,true);const seed=r.relationSeeds.find(q=>q.key===p.key);for(const state of ['initial','after'])for(const kind of ['vertex','area']){const counts={inside:0,outside:0,'surface-band':0,ambiguous:0};p.queries.forEach((q,i)=>{if(seed.queries[i].kind===kind)counts[q[state].kind]++;});assert.deepEqual(counts,p[kind==='vertex'?'vertices':'area'][state]);assert.equal(counts.ambiguous,0);}}
});
test('unchanged crossing total cannot hide new skin and bone regressions',()=>{
  const s=r.summary;assert.equal(s.vertices,652173);assert.equal(s.initialOutside,3882);assert.equal(s.afterOutside,3409);assert.equal(s.newOutside,122);assert.equal(s.worsenedOutside,1199);assert.equal(s.examinedPairs,89794);assert.equal(s.currentPairs,232);assert.equal(s.initialPairs,196);assert.equal(s.afterPairs,196);assert.equal(s.newAgainst_initial,4);assert.equal(s.newAgainst_current,87);
  const fresh=r.relations.filter(p=>p.after&&!p.initial);assert.deepEqual(fresh.map(p=>p.ids),[['HRAF0828','VHF0034'],['HRAF0954','VHF0016'],['HRAF0954','VHF0017'],['HRAF0954','VHF0019']]);assert.ok(fresh.every(p=>p.interiorWitness));assert.deepEqual(fresh.map(p=>p.current),[true,true,true,false]);assert.equal(r.relations.filter(p=>p.initial&&!p.after).length,4);assert.equal(s.sourceInternalPairs,33);assert.equal(s.initialInternalPairs,34);assert.equal(s.afterInternalPairs,34);assert.equal(s.newInternalAgainstInitial,0);assert.equal(s.newInternalAgainstSource,1);assert.equal(s.afterSourceBonePairs,23);assert.ok(r.sourceBoneRelations.every(p=>p.source===p.initial&&p.initial===p.after));assert.deepEqual(r.bones.filter(p=>p.after.forward.p95Mm>p.before.forward.p95Mm).map(p=>p.name),['left-Pelvis','right-Patella']);
});
test('scalar replay preserves explicit full-coordinate and bounded relation-query scope',()=>{
  assert.equal(a.reportSha256,sha(read(dir+'hip-relational-flow.json')));assert.equal(a.scriptSha256,sha(read('scripts/verify-hip-relational-flow.mjs')));assert.equal(a.candidateSha256,r.binary.sha256);assert.equal(a.vertices,652173);assert.equal(a.indexReferences,3912126);assert.equal(a.coordinateDifferences,0);assert.equal(a.boneVertices,471211);assert.equal(a.boneIndexReferences,2827170);assert.equal(a.jacobianSamples,9728);assert.equal(a.sampling.surfaces,110);assert.equal(a.sampling.samples,10624);assert.equal(a.sampling.inputTriangles,2257221);assert.equal(a.reverseMaterialPoints,1536);assert.deepEqual(a.skinExtremes,{vertices:652173,outside:3882,selected:404});assert.equal(a.relationReplay.pairs,10);assert.equal(a.relationReplay.queries,8810);assert.equal(a.relationReplay.materialPoints,365);assert.ok(a.relationReplay.maximumMaterialResidualMm<1e-7);assert.equal(a.relationReplay.maximumTargetResidualMm,0);assert.equal(a.witnesses,5);assert.equal(a.missingWitnesses,0);assert.ok(a.controlLossReplay.every(p=>p.lossResidual<1e-19));
  for(const f of r.files.filter(p=>!p.file.startsWith('.cache/')))assert.equal(sha(read(f.file)),f.sha256,f.file);const review=json(dir+'hip-relational-flow-agy-review.json');assert.equal(review.response.status,'SUCCESS');assert.equal(review.corrections.length,7);
});
test('four pelvic views retain34 equal structures without treating transparency as containment evidence',()=>{
  assert.equal(c.reportSha256,a.reportSha256);assert.equal(c.priorReportSha256,r.priorSha256);assert.equal(c.auditSha256,sha(read(dir+'hip-relational-flow-readback.json')));assert.equal(c.scriptSha256,sha(read('scripts/capture-hip-relational-flow.mjs')));assert.deepEqual(c.errors,[]);assert.equal(c.captures.length,4);const muscleIds=new Set(r.relationSeeds.map(p=>p.muscleId)),ids=[...r.muscles.filter(p=>muscleIds.has(p.id)).map(p=>p.id),...new Set(r.bones.filter(p=>p.name.endsWith('Pelvis')||p.name.startsWith('VERTEBRA')).flatMap(p=>p.targetIds)),...new Set(r.relationSeeds.map(p=>p.targetId))];assert.equal(ids.length,34);
  for(const view of ['front','oblique']){const group=c.captures.filter(p=>p.view===view);assert.deepEqual(group.map(p=>p.state),['initial','flow']);for(const p of group){assert.deepEqual(p.ids,ids);assert.deepEqual(p.cameraPosition,group[0].cameraPosition);assert.deepEqual(p.target,group[0].target);assert.equal(p.extent,group[0].extent);assert.equal(sha(read(dir+p.file)),p.sha256);}}assert.match(c.limits,/Transparency does not establish inside\/outside/);
});
