# Male Z-Anatomy vessels that the female HRA source already models, paired
# with the HRA vessels of the same name (groups where one source splits a
# vessel the other keeps whole). Used as field correspondences and to measure
# the junctions between carried branches and the female trunks.
PAIRS = [
    (["Ascending aorta"], ["Ascending aorta"]),
    (["Aortic arch"], ["Aortic arch"]),
    (["Thoracic aorta", "Abdominal aorta"], ["Descending aorta a", "Descending aorta b"]),
    (["Brachiocephalic trunk"], ["Brachiocephalic artery a", "Brachiocephalic artery b"]),
    (["Left common carotid artery"], ["Left common carotid artery a", "Left common carotid artery b"]),
    (["Left subclavian artery"], ["Left subclavian artery a", "Left subclavian artery b"]),
    (["Pulmonary trunk", "Bifurcation of pulmonary trunk"], ["Pulmonary trunk"]),
    (["Right pulmonary artery"], ["Pulmonary artery (right)"]),
    (["Left pulmonary artery"], ["Pulmonary artery (left)"]),
    (["Right superior pulmonary vein"], ["Pulmonary vein superior (right)"]),
    (["Right inferior pulmonary vein"], ["Pulmonary vein inferior (right)"]),
    (["Left superior pulmonary vein"], ["Pulmonary vein superior (left)"]),
    (["Left inferior pulmonary vein"], ["Pulmonary vein inferior (left)"]),
    (["Superior vena cava"], ["Superior vena cava"]),
    (["Inferior vena cava (abdominal part)", "Inferior vena cava (thoracic part)"], ["Inferior vena cava a", "Inferior vena cava b"]),
    (["Coeliac trunk"], ["Celiac trunk"]),
    (["Superior mesenteric artery"], ["Superior mesenteric artery"]),
    (["Inferior mesenteric artery"], ["Inferior mesenteric artery"]),
    (["Superior mesenteric vein"], ["Superior mesenteric vein"]),
    (["Inferior mesenteric vein"], ["Inferior mesenteric vein"]),
    (["Right colic artery"], ["Right colic artery"]), (["Middle colic artery"], ["Middle colic artery"]), (["Left colic artery"], ["Left colic artery"]),
    (["Right colic vein"], ["Right colic vein"]), (["Middle colic vein"], ["Middle colic vein"]),
    (["Ileocolic artery"], ["Ileocolic artery"]),
    (["Sigmoid arteries"], ["Sigmoid artery a", "Sigmoid artery b", "Sigmoid artery c"]),
    (["Sigmoid veins"], ["Sigmoid vein a", "Sigmoid vein b", "Sigmoid vein c"]),
    (["Superior anorectal artery"], ["Superior rectal artery"]),
    (["Marginal artery"], ["Marginal artery of Drummond"]),
    (["Splenic artery"], ["Splenic artery"]), (["Splenic vein"], ["Splenic vein"]),
    (["Common hepatic artery"], ["Common hepatic artery"]), (["Proper hepatic artery"], ["Proper hepatic artery"]),
    (["Hepatic veins"], ["Right hepatic vein", "Middle hepatic vein", "Left hepatic vein"]),
    (["Hepatic portal vein"], ["Hepatic portal vein", "Right branch of portal vein", "Left branch of portal vein"]),
    (["Right renal artery"], ["Right renal artery"]), (["Left renal artery"], ["Left renal artery"]),
    (["Right renal vein"], ["Right renal vein"]), (["Left renal vein"], ["Left renal vein"]),
    (["Common iliac vein (left)"], ["Left common iliac vein"]), (["Common iliac vein (right)"], ["Right common iliac vein"]),
    (["Internal iliac vein (left)"], ["Internal iliac vein (left)"]), (["Internal iliac vein (right)"], ["Internal iliac vein (right)"]),
    (["Internal pudendal vein (left)"], ["Internal pudendal vein (left)"]), (["Internal pudendal vein (right)"], ["Internal pudendal vein (right)"]),
    (["Right coronary artery"], ["Right coronary artery"]), (["Left coronary artery"], ["Left coronary artery"]),
    (["Anterior interventricular artery"], ["Left anterior descending artery"]), (["Circumflex artery of heart"], ["Left circumflex artery"]),
    (["Coronary sinus"], ["Coronary sinus"]), (["Great cardiac vein"], ["Great cardiac vein"]), (["Middle cardiac vein"], ["Middle cardiac vein"]),
]
