import assert from 'node:assert/strict';
// Pivoted Gaussian elimination for the small centred least-squares systems.
function solve(a,b){const m=a.map((r,i)=>[...r,b[i]]),n=b.length;for(let k=0;k<n;k++){let pivot=k;for(let i=k+1;i<n;i++)if(Math.abs(m[i][k])>Math.abs(m[pivot][k]))pivot=i;assert.ok(Math.abs(m[pivot][k])>1e-14,'Rank-deficient sphere fit');[m[k],m[pivot]]=[m[pivot],m[k]];const d=m[k][k];for(let j=k;j<=n;j++)m[k][j]/=d;for(let i=0;i<n;i++)if(i!==k){const t=m[i][k];for(let j=k;j<=n;j++)m[i][j]-=t*m[k][j];}}return m.map(r=>r[n]);}
function leastSquares(rows,values){const a=Array.from({length:4},()=>[0,0,0,0]),b=[0,0,0,0];for(let n=0;n<rows.length;n++)for(let i=0;i<4;i++){b[i]+=rows[n][i]*values[n];for(let j=0;j<4;j++)a[i][j]+=rows[n][i]*rows[n][j];}return solve(a,b);}
export function fitSphere(points){
  assert.ok(points.length>=4&&points.every(p=>p.length===3&&p.every(Number.isFinite)));const origin=[0,1,2].map(k=>points.reduce((s,p)=>s+p[k],0)/points.length),scale=Math.sqrt(points.reduce((s,p)=>s+p.reduce((s,v,k)=>s+(v-origin[k])**2,0),0)/points.length);assert.ok(scale>0);
  const q=points.map(p=>p.map((v,k)=>(v-origin[k])/scale)),seed=leastSquares(q.map(p=>[2*p[0],2*p[1],2*p[2],1]),q.map(p=>p.reduce((s,v)=>s+v*v,0)));let centre=seed.slice(0,3),radius=Math.sqrt(seed[3]+centre.reduce((s,v)=>s+v*v,0));assert.ok(radius>0&&Number.isFinite(radius));let termination='iteration-limit';const history=[];
  for(let iteration=0;iteration<40;iteration++){const rows=[],values=[];for(const p of q){const d=p.map((v,k)=>centre[k]-v),length=Math.hypot(...d);assert.ok(length>1e-12);rows.push([...d.map(v=>v/length),-1]);values.push(radius-length);}const delta=leastSquares(rows,values),loss=(c,r)=>q.reduce((s,p)=>s+(Math.hypot(...p.map((v,k)=>v-c[k]))-r)**2,0)/q.length;let step=1,next,nextRadius;while(step>=1/1024){next=centre.map((v,k)=>v+step*delta[k]);nextRadius=radius+step*delta[3];if(nextRadius>0&&loss(next,nextRadius)<=loss(centre,radius)+1e-20)break;step/=2;}if(step<1/1024){termination='no-improving-step';break;}const change=scale*Math.max(Math.hypot(...next.map((v,k)=>v-centre[k])),Math.abs(nextRadius-radius));centre=next;radius=nextRadius;history.push({iteration,maximumParameterChangeMetres:change,rmsMetres:Math.sqrt(loss(centre,radius))*scale});if(change<1e-10){termination='parameter-change-threshold';break;}}
  const result=centre.map((v,k)=>origin[k]+v*scale),r=radius*scale,residuals=points.map(p=>Math.abs(Math.hypot(...p.map((v,k)=>v-result[k]))-r)).sort((a,b)=>a-b);return {centre:result,radius:r,termination,history,residual:{count:points.length,rmsMm:1000*Math.sqrt(residuals.reduce((s,v)=>s+v*v,0)/points.length),p95Mm:1000*residuals[Math.floor(points.length*.95)],maximumMm:1000*residuals.at(-1)}};
}
